<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Usuario_model');
        
    }

    function index()
    {
        $data['_view'] = 'dashboard';
        $id=0;
        $data['permiso'] = $this->Usuario_model->obtener_permisos($id);
        
        $data['usuario'] = $this->session->get_UserData('');
        $this->load->view('layouts/main',$data);
    }
    function login()
    {
        $this->load->view('login/login');
    }
}
