<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Empresa extends CI_Controller{

    var $campos_datatable= 'id,razon_social,rut,dv';
    var $table='empresas';
    var $id_tabla='id';
    var $opc_editar;
    var $opc_borrar;
    var $btn_agregar;
    var $permisos=array();
    var $modulo = "EMPRESAS";// NOMBRE DEL MODULO EN LA BASE DE DATOS
    
    function __construct()
        {
            parent::__construct();
            $this->load->model('Empresa_model');
            if(!is_logged_in())
            {
                $this->session->sess_destroy();
                redirect("login");   
            }
                //$salida=generar_permisos($this->modulo,$this->session->id_usuario,'Agregar Empresa');
            $salida=generar_permisos($this->modulo,100,' Agregar Empresa');
            //var_dump($salida);
            $this->permisos=$salida['permisos'];
            $this->opc_editar=$salida['botones']['opc_editar'];
            $this->opc_borrar=$salida['botones']['opc_borrar'];
            $this->btn_agregar=$salida['botones']['boton_agregar'];
        } 

    /*
     * Listing of empresas
     */
    function index()
    {
        $js=array('resources/js/modules/empresa.js',
                        'resources/modules/datatables/datatables.min.js',
                        'resources/modules/datatables/dataTables.editor.min.js',
                        "resources/modules/izitoast/js/iziToast.js",
                        );
        $css=array('resources/modules/izitoast/css/iziToast.min.css');


        $data['empresas'] = $this->Empresa_model->get_all_empresas(null);
        
        $data['_view'] = 'empresa/index';
        
        $data['usuario'] = $this->session->get_UserData('');
        $data['js'] = $js;
        $data['css'] = $css;
        $data['btn_add']=$this->btn_agregar;
        $data['modal_add']=$this->load->view('empresa/add',null,true);
        //var_dump($modal_add);
        $this->load->view('layouts/main',$data);

    }

    public function listar() 
        {
            $campo_id ='idcuentas';
            $salida=array();

            // Output data as json format
            $this->load->library('Datatables');
            $this->datatables->select($this->campos_datatable)->from($this->table);
            $this->datatables->add_column('acciones',"$this->opc_editar"."$this->opc_borrar", $this->id_tabla);

            $salida=$this->datatables->generate();
            echo $salida;
        }


    /*
     * Adding a new empresa
     */
    function add()
    {
        $params = array(
				'rut' => $this->input->post('rut'),
				'dv' => $this->input->post('dv'),
				'razon_social' => $this->input->post('razon_social'),
            );
            
        $empresa_id = $this->Empresa_model->add_empresa($params);
        if ($empresa_id)
            $data['success']=true;
        else
            $data['success']=false;
           // var_dump($data);
        echo json_encode($data);
    }  

    /*
     * Editing a empresa
     */
    function edit()
    {   
        // check if the empresa exists before trying to edit it
        //if(isset($_POST)
        $id=$this->input->post('id');

        $data['db'] = $this->Empresa_model->get_empresa($id);
        //var_dump($data);
        
        if(isset($data['db']['id']))
        {
            echo json_encode($data);
        }
        else
            show_error('The empresa you are trying to edit does not exist.');
    } 

    function update()
    {   
        // check if the empresa exists before trying to edit it
        //if(isset($_POST)
        $id=$this->input->post('id_empresa');

            $params = array(
                'rut' => $this->input->post('rut'),
                'dv' => $this->input->post('dv'),
                'razon_social' => $this->input->post('razon_social'),
            );

        $result= $this->Empresa_model->update_empresa($id,$params);
        if(isset($result))
        {
             echo json_encode($result);
        }
        else
            show_error('The empresa you are trying to edit does not exist.');
    } 

    /*
     * Deleting empresa
     */
    function remove()
    {
        $id=$this->input->post('id_empresa');
        $empresa = $this->Empresa_model->get_empresa($id);

        // check if the empresa exists before trying to delete it
        if(isset($empresa['id']))
        {
            $result=$this->Empresa_model->delete_empresa($id);
            if ($result)
                $salida['success']=true;
            else
                $salida['success']=false;
            echo json_encode($salida);
            
        }
        else
            show_error('The empresa you are trying to delete does not exist.');
    }
    
}
