<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Timbraje extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Timbraje_model');
    } 

    /*
     * Listing of timbraje
     */
    function index()
    {
        $data['timbraje'] = $this->Timbraje_model->get_all_timbraje();
        
        $data['_view'] = 'timbraje/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new timbraje
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nulo' => $this->input->post('nulo'),
				'id_tipo_libro' => $this->input->post('id_tipo_libro'),
				'id_cliente' => $this->input->post('id_cliente'),
				'desde' => $this->input->post('desde'),
				'hasta' => $this->input->post('hasta'),
				'mes' => $this->input->post('mes'),
				'anio' => $this->input->post('anio'),
				'id_comprobante' => $this->input->post('id_comprobante'),
            );
            
            $timbraje_id = $this->Timbraje_model->add_timbraje($params);
            redirect('timbraje/index');
        }
        else
        {
			$this->load->model('Tipos_libro_model');
			$data['all_tipos_libros'] = $this->Tipos_libro_model->get_all_tipos_libros();

			$this->load->model('Empresa_model');
			$data['all_empresas'] = $this->Empresa_model->get_all_empresas();
            
            $data['_view'] = 'timbraje/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a timbraje
     */
    function edit($id)
    {   
        // check if the timbraje exists before trying to edit it
        $data['timbraje'] = $this->Timbraje_model->get_timbraje($id);
        
        if(isset($data['timbraje']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nulo' => $this->input->post('nulo'),
					'id_tipo_libro' => $this->input->post('id_tipo_libro'),
					'id_cliente' => $this->input->post('id_cliente'),
					'desde' => $this->input->post('desde'),
					'hasta' => $this->input->post('hasta'),
					'mes' => $this->input->post('mes'),
					'anio' => $this->input->post('anio'),
					'id_comprobante' => $this->input->post('id_comprobante'),
                );

                $this->Timbraje_model->update_timbraje($id,$params);            
                redirect('timbraje/index');
            }
            else
            {
				$this->load->model('Tipos_libro_model');
				$data['all_tipos_libros'] = $this->Tipos_libro_model->get_all_tipos_libros();

				$this->load->model('Empresa_model');
				$data['all_empresas'] = $this->Empresa_model->get_all_empresas();

                $data['_view'] = 'timbraje/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The timbraje you are trying to edit does not exist.');
    } 

    /*
     * Deleting timbraje
     */
    function remove($id)
    {
        $timbraje = $this->Timbraje_model->get_timbraje($id);

        // check if the timbraje exists before trying to delete it
        if(isset($timbraje['id']))
        {
            $this->Timbraje_model->delete_timbraje($id);
            redirect('timbraje/index');
        }
        else
            show_error('The timbraje you are trying to delete does not exist.');
    }
    
}
