<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipos_libro extends CI_Controller{
    var $campos_datatable= 'id,nombre,activo';
    var $table='tipos_libros';
    var $id_tabla='id';
    var $opciones_editar;
    var $opciones_borrar;
    var $permisos=array();
    var $modulo = "TIPOS_LIBROS";// NOMBRE DEL MODULO EN LA BASE DE DATOS

    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipos_libro_model');
        $salida=generar_permisos($this->modulo,100,' Agregar nuevo Libro');
        //var_dump($salida);
        $this->permisos=$salida['permisos'];
        $this->opc_editar=$salida['botones']['opc_editar'];
        $this->opc_borrar=$salida['botones']['opc_borrar'];
        $this->btn_agregar=$salida['botones']['boton_agregar'];
    } 

    /*
     * Listing of tipos_libros
     */
    function index()
    {

        $js=array('resources/js/modules/tipos_libros.js',
                        'resources/modules/datatables/datatables.min.js',
                        'resources/modules/datatables/dataTables.editor.min.js',
                        "resources/modules/izitoast/js/iziToast.js",
                        );
        $css=array('resources/modules/izitoast/css/iziToast.min.css');

        $data['usuario'] = $this->session->get_UserData('');
        $data['js'] = $js;
        $data['css'] = $css;
        $data['modal_add']=$this->load->view('empresa/add',null,true);

        $data['tipos_libros'] = $this->Tipos_libro_model->get_all_tipos_libros();
        
        $data['_view'] = 'tipos_libro/index';

        $data['usuario'] = $this->session->get_UserData('');
        $data['js'] = $js;
        $data['css'] = $css;
        $data['btn_add']=$this->btn_agregar;
        $data['modal_add']=$this->load->view('tipos_libro/add',null,true);
        //var_dump($modal_add);
        $this->load->view('layouts/main',$data);        
    }

    public function listar() 
        {
            $campo_id ='id';
            $salida=array();

            // Output data as json format
            $this->load->library('Datatables');
            $this->datatables->select($this->campos_datatable)->from($this->table);
            //$this->datatables->add_column('en_uso',"es_activo", $this->id_tabla);
            $this->datatables->add_column('acciones',"$this->opc_editar"."$this->opc_borrar", $this->id_tabla);

            $salida=$this->datatables->generate();
            echo $salida;
        }


    /*
     * Adding a new tipos_libro
     */
    function add()
    {   
        $params = array(
            'activo' => $this->input->post('activo'),
            'nombre' => $this->input->post('nombre'),
        );

        $resultado = $this->Tipos_libro_model->add_tipos_libro($params);
        if ($resultado)
            $data['success']=true;
        else
            $data['success']=false;
           // var_dump($data);
        echo json_encode($data);
    }  


    function update()
    {   
        // check if the empresa exists before trying to edit it
        //var_dump($_POST);
        $id=$this->input->post('id_current');
        if ($this->input->post('activo')==1)
            $activo=1;
        else
            $activo=0;

        $params = array(
            'activo' => $activo,
            'nombre' => $this->input->post('nombre'),
        );
        //var_dump($params);
        $result= $this->Tipos_libro_model->update_tipos_libro($id,$params);
        $data['success']=false;
        if(isset($result))
            {
                $data['success']=true;
            }
        else
            $data['message']='No existe el Tipo de libro que queire actualizar';

        echo json_encode($data);
    } 
    /*
     * Editing a tipos_libro
     */
    function edit()
    {   
        // check if the empresa exists before trying to edit it
        //if(isset($_POST)
        $id=$this->input->post('id');

        //var_dump($data);
        
        $data['db'] = $this->Tipos_libro_model->get_tipos_libro($id);
        if(isset($data['db'][$this->id_tabla]))
        {
            echo json_encode($data);
        }
        else
            show_error('The empresa you are trying to edit does not exist.');

    } 

    /*
     * Deleting tipos_libro
     */

    function remove()
    {
        $id=$this->input->post('id_to_delete');
        $resultado = $this->Tipos_libro_model->get_tipos_libro($id);

        // check if the empresa exists before trying to delete it
        if(isset($resultado[$this->id_tabla]))
        {
            $result=$this->Tipos_libro_model->delete_tipos_libro($id);
            if ($result)
                $salida['success']=true;
            else
                $salida['success']=false;
            echo json_encode($salida);
            
        }
        else
            show_error('The tipos_libro you are trying to delete does not exist.');
    }
    
}
