<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usuario extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Usuario_model');
        if(!is_logged_in())
        {
            $this->session->sess_destroy();
            redirect("login");   
        }
    } 

    /*
     * Listing of usuarios
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('usuario/index?');
        $config['total_rows'] = $this->Usuario_model->get_all_usuarios_count();
        $this->pagination->initialize($config);

        $data['usuarios'] = $this->Usuario_model->get_all_usuarios($params);
        
        $data['_view'] = 'usuario/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new usuario
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('username','Username','required');
		$this->form_validation->set_rules('clave','Clave','required');
		$this->form_validation->set_rules('email','Email','required|valid_email');
		
		if($this->form_validation->run())     
        {   
            $edit= $this->input->post('editar')!=null ? $this->input->post('editar') : 0;
            $borrar = $this->input->post('borrar')!=null ? $this->input->post('borrar') : 0;

            $params = array(
				'activo' => $this->input->post('activo'),
				'email' => $this->input->post('email'),
				'username' => $this->input->post('username'),
                'clave' => $this->input->post('clave'),
                'kn_edit_timbraje' => $edit,
                'kn_borrar_timbraje' => $borrar ,
            );
            
            $usuario_id = $this->Usuario_model->add_usuario($params);
            redirect('usuario/index');
        }
        else
        {            
            $data['_view'] = 'usuario/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a usuario
     */
    function edit($id)
    {   
        // check if the usuario exists before trying to edit it
        $data['usuario'] = $this->Usuario_model->get_usuario($id);
        $data['permiso'] = $this->Usuario_model->obtener_permisos($id);
        
        if(isset($data['usuario']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('username','Username','required');
			$this->form_validation->set_rules('clave','Clave','required');
			$this->form_validation->set_rules('email','Email','required|valid_email');
		
			if($this->form_validation->run())     
            {   
                $edit= $this->input->post('editar')!=null ? $this->input->post('editar') : 0;
                $borrar = $this->input->post('borrar')!=null ? $this->input->post('borrar') : 0;
                $params = array(
					'activo' => $this->input->post('activo'),
					'email' => $this->input->post('email'),
					'username' => $this->input->post('username'),
					'clave' => $this->input->post('clave'),
                    'kn_edit_timbraje' => $edit,
                    'kn_borrar_timbraje' => $borrar,
                );

                $this->Usuario_model->update_usuario($id,$params);            
                redirect('usuario/index');
            }
            else
            {
                $data['_view'] = 'usuario/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The usuario you are trying to edit does not exist.');
    } 

    /*
     * Deleting usuario
     */
    function remove($id)
    {
        $usuario = $this->Usuario_model->get_usuario($id);

        // check if the usuario exists before trying to delete it
        if(isset($usuario['id']))
        {
            $this->Usuario_model->delete_usuario($id);
            redirect('usuario/index');
        }
        else
            show_error('The usuario you are trying to delete does not exist.');
    }
    
}
