<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Comprobantes_timbraje_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get comprobantes_timbraje by id
     */
    function get_comprobantes_timbraje($id)
    {
        return $this->db->get_where('comprobantes_timbraje',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all comprobantes_timbraje count
     */
    function get_all_comprobantes_timbraje_count()
    {
        $this->db->from('comprobantes_timbraje');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all comprobantes_timbraje
     */
    function get_all_comprobantes_timbraje($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('comprobantes_timbraje')->result_array();
    }
        
    /*
     * function to add new comprobantes_timbraje
     */
    function add_comprobantes_timbraje($params)
    {
        $this->db->insert('comprobantes_timbraje',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update comprobantes_timbraje
     */
    function update_comprobantes_timbraje($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('comprobantes_timbraje',$params);
    }
    
    /*
     * function to delete comprobantes_timbraje
     */
    function delete_comprobantes_timbraje($id)
    {
        return $this->db->delete('comprobantes_timbraje',array('id'=>$id));
    }

    /*
    */
    function verifica_rango_desde($id_empresa,$desde)
    {
        $misql='select * from timbraje where id_cliente='.$id_empresa.' and ('.$desde.' between desde and hasta) ';
        return $this->db->query($misql)->result_array();
    }
    
    function verifica_rango_hasta($id_empresa,$hasta)
    {
        $misql=' select * from timbraje where id_cliente='.$id_empresa.' and ('.$hasta.' between desde and hasta) ';
        return $this->db->query($misql)->result_array();
    }
    
    function verifica_tipo_mes_anio($id_empresa,$tipo_libro,$mes,$anio)
    {
        $misql=' select * from timbraje where id_cliente='.$id_empresa.' and ('.$tipo_libro.'=id_tipo_libro) and (mes='.$mes.' and anio='.$anio.')';
        return $this->db->query($misql)->result_array();
    }

    
    function verifica_tipo_periodo($id_empresa,$tipo_libro,$periodo)
    {
        $misql=' select * from timbraje where id_cliente='.$id_empresa.' and ('.$tipo_libro.'=id_tipo_libro) and ('.$periodo.' between peroido1 and periodo2)';
        return $this->db->query($misql)->result_array();
    }

}