<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Timbraje_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get timbraje by id
     */
    function get_timbraje($id)
    {
        return $this->db->get_where('timbraje',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all timbraje
     */
    function get_all_timbraje()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('timbraje')->result_array();
    }
        
    /*
     * function to add new timbraje
     */
    function add_timbraje($params)
    {
        $this->db->insert('timbraje',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update timbraje
     */
    function update_timbraje($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('timbraje',$params);
    }
    
    /*
     * function to delete timbraje
     */
    function delete_timbraje($id)
    {
        return $this->db->delete('timbraje',array('id'=>$id));
    }
}
