<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipos_libro_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipos_libro by id
     */
    function get_tipos_libro($id)
    {
        return $this->db->get_where('tipos_libros',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tipos_libros
     */
    function get_all_tipos_libros()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tipos_libros')->result_array();
    }
        
    /*
     * function to add new tipos_libro
     */
    function add_tipos_libro($params)
    {
        $this->db->insert('tipos_libros',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipos_libro
     */
    function update_tipos_libro($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tipos_libros',$params);
    }
    
    /*
     * function to delete tipos_libro
     */
    function delete_tipos_libro($id)
    {
        return $this->db->delete('tipos_libros',array('id'=>$id));
    }
}
