-- Generated by CRUDigniter v2.3 Beta 
-- www.crudigniter.com

-- Generation Time: Sep 21, 2020 06:41 PM

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Table structure for table `comprobantes_timbraje`
--

DROP TABLE IF EXISTS `comprobantes_timbraje`;
CREATE TABLE `comprobantes_timbraje` (
`id` int(11) NOT NULL,
`fecha` date NOT NULL,
`id_usuario` int(11) NOT NULL,
`id_empresa` int(255) 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `comprobantes_timbraje`
--

ALTER TABLE `comprobantes_timbraje`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `comprobantes_timbraje`
--

ALTER TABLE `comprobantes_timbraje`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `empresas`
--

DROP TABLE IF EXISTS `empresas`;
CREATE TABLE `empresas` (
`id` bigint(20) NOT NULL,
`rut` int(20) NOT NULL,
`dv` varchar(2) NOT NULL,
`razon_social` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `empresas`
--

ALTER TABLE `empresas`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `empresas`
--

ALTER TABLE `empresas`
MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `timbraje`
--

DROP TABLE IF EXISTS `timbraje`;
CREATE TABLE `timbraje` (
`id` bigint(20) NOT NULL,
`id_tipo_libro` int(11) NOT NULL,
`nulo` tinyint(1) NOT NULL,
`id_cliente` bigint(20) NOT NULL,
`desde` int(11) NOT NULL,
`hasta` int(11) NOT NULL,
`mes` int(11) NOT NULL,
`anio` int(11) NOT NULL,
`id_comprobante` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `timbraje`
--

ALTER TABLE `timbraje`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `timbraje`
--

ALTER TABLE `timbraje`
MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `tipos_libros`
--

DROP TABLE IF EXISTS `tipos_libros`;
CREATE TABLE `tipos_libros` (
`id` bigint(20) NOT NULL,
`nombre` varchar(50) NOT NULL,
`activo` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `tipos_libros`
--

ALTER TABLE `tipos_libros`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `tipos_libros`
--

ALTER TABLE `tipos_libros`
MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `usuarios`
--

DROP TABLE IF EXISTS `usuarios`;
CREATE TABLE `usuarios` (
`id` int(11) NOT NULL,
`username` varchar(50) NOT NULL,
`clave` varchar(256) NOT NULL,
`activo` tinyint(1) NOT NULL,
`email` varchar(255) 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `usuarios`
--

ALTER TABLE `usuarios`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `usuarios`
--

ALTER TABLE `usuarios`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
